version: '3.7'

services:
  stock-service:
    build:
      context: ./stock-service
      dockerfile: ../Dockerfile
    volumes:
      - ./stock-service:/app
      - /app/node_modules
    ports:
      - 3001:3001

  api-service:
    build:
      context: ./api-service
      dockerfile: ../Dockerfile
    command: >
      sh -c "npm install && npm run db:fresh && npm run start" 
    volumes:
      - ./api-service:/app
      - /app/node_modules
    ports:
      - 3002:3002
    depends_on:
      - postgres
  
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
